##################################################
# RFNoC Sources
##################################################

RFNOC_SRCS += $(addprefix $(RFNOC_PFB_CHANNELIZER_DIR)/fpga-src/, \
noc_block_chanmux.v \
)
